### ISSUE TITLE
Request: Can this be done in reverse?

### ISSUE THREAD

**Issue by tareko** [lukasmu/nextcloud-s3-to-disk-migration#5]
Hello,

I am trying to do the reverse process. Would you be willing to rewrite this script to do that, as my programming skills are not very strong.

I'm happy to pay a bounty for this if so!

tarek : )

**Comment by lukasmu** [comment]
This should be possible. However, I cannot really recommend it. I initially created this script to migrate away from S3 based primary storage because I had way too many issues with it. Are you really sure that you want to do this?

**Comment by tareko** [comment]
What are the issues that you had? I have >120gb of files shared among about 100 users of whom ~20 are active, which is why I want to do this. Mostly so that I can migrate to a proper Digital Ocean kubernetes setup, which is much easier with S3 than with a local storage. I plan on using Digital Ocean Spaces, which is their S3-compatible setup.

**Comment by lukasmu** [comment]
The main issue I faced was related to orphaned files being stored in the S3 bucket: failed uploads, deleted files, thumbnails, previews, ... When I was using the S3 as primary storage Nextcloud featured no proper function to remove orphaned files from the S3 bucket. Hence, the S3 bucket quickly became large (and expensive). I doubt that this has changed in the meantime (see e.g. https://help.nextcloud.com/t/s3-as-primary-storage-not-cleaned-suspect-issue-with-cron-on-one-com-missing-posix/130367/2).
I also regularly faced upload issues. Streaming videos or serving folders with many files was problematic as well. 

When I switched to local storage I immediately got less errors in the Nextcloud log. Also debugging issues seems easier (e.g. when a file seems to be corrupted in the Nextcloud interface one can easily get the original from the disk). Lastly, local storage allowed me to use my default backup strategy (instead of setting up an additional backup strategy for S3 storage).

Note 1: Back in the times I used DO Spaces as well. But the issues are rather generic and not related to a specific S3 storage vendor. 
Note 2: I think DO is really expensive with regards to disk space. Unfortunately, at this moment they do only offer Volumes which are SSD-based. Other providers also offer way cheaper HDD-based storage solutions which are often perfectly fine for storing Nextcloud files.

**Comment by tareko** [comment]
OK, I think you've convinced me. The last argument against is the use of the URN/OID naming strategy, which while giving good performance makes it so that if nextcloud or the database die (or it's years later), it's a tangled mess. I'm considering using S3QL instead to get the benefits of cheap storage with a proper file system and the other benefits you mention..

**Comment by lukasmu** [comment]
This could indeed be a good alternative. I wish you success with it!
